-- UniVote - Full Database Setup (Postgres/Supabase)
-- Run this whole script in the Supabase SQL editor.

-- 1) Extensions (for UUIDs)
create extension if not exists pgcrypto;

-- 2) Tables

-- 2.1 polls
create table if not exists public.polls (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  type text not null check (type in ('single', 'multiple', 'party')),
  options jsonb not null default '[]'::jsonb,
  parties jsonb,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create index if not exists idx_polls_starts_at on public.polls (starts_at);
create index if not exists idx_polls_ends_at on public.polls (ends_at);

-- 2.2 votes (anonymous; stores chosen option IDs)
create table if not exists public.votes (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.polls(id) on delete cascade,
  option_ids text[] not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_votes_poll_id on public.votes (poll_id);

-- 2.3 invites (used by the app to invite users by email)
create table if not exists public.invites (
  id bigint generated by default as identity primary key,
  email text not null,
  token uuid not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists uq_invites_token on public.invites(token);

-- 3) Helper function to check if user is admin
-- This function checks user_metadata.role from auth.users
create or replace function public.is_admin()
returns boolean
language plpgsql
security definer
stable
as $$
begin
  return (
    select (raw_user_meta_data->>'role')::text = 'admin'
    from auth.users
    where id = auth.uid()
  );
end;
$$;

-- 4) Row Level Security (RLS)
alter table public.polls enable row level security;
alter table public.votes enable row level security;
alter table public.invites enable row level security;

-- 4.1 polls policies
drop policy if exists polls_select_all on public.polls;
create policy polls_select_all
  on public.polls
  for select
  using (
    -- Anyone logged-in can see published polls; admins/owners see all
    (published = true)
    or public.is_admin()
    or (created_by = auth.uid())
  );

drop policy if exists polls_insert_admin on public.polls;
create policy polls_insert_admin
  on public.polls
  for insert
  with check (public.is_admin());

drop policy if exists polls_update_admin on public.polls;
create policy polls_update_admin
  on public.polls
  for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists polls_delete_admin on public.polls;
create policy polls_delete_admin
  on public.polls
  for delete
  using (public.is_admin());

-- 4.2 votes policies
drop policy if exists votes_insert_active_authenticated on public.votes;
create policy votes_insert_active_authenticated
  on public.votes
  for insert
  with check (
    auth.uid() is not null
    and exists (
      select 1 from public.polls p
      where p.id = poll_id
        and p.starts_at <= now()
        and p.ends_at   >= now()
    )
  );

drop policy if exists votes_select_published_or_admin on public.votes;
create policy votes_select_published_or_admin
  on public.votes
  for select
  using (
    exists (
      select 1 from public.polls p
      where p.id = poll_id
        and (
          p.published = true
          or public.is_admin()
        )
    )
  );

-- (No update/delete on votes by default)

-- 4.3 invites policies (admin only)
drop policy if exists invites_admin_all on public.invites;
create policy invites_admin_all
  on public.invites
  using (public.is_admin())
  with check (public.is_admin());

-- 5) Realtime
-- In Supabase dashboard, enable Realtime for schemas/tables: polls, votes
-- (Database > Replication > configure) so the app receives live updates.

-- 6) Optional seed data (comment out in production)
-- insert into public.polls (title, description, type, options, parties, starts_at, ends_at, published)
-- values (
--   'Student Representative Council',
--   'Elect the SRC President and Deputy President',
--   'party',
--   '[]',
--   '[{"id":"00000000-0000-0000-0000-000000000001","name":"Progressive Students Alliance","president":{"id":"00000000-0000-0000-0000-000000000011","name":"Alex Johnson"},"deputyPresident":{"id":"00000000-0000-0000-0000-000000000012","name":"Sarah Williams"}}]'::jsonb,
--   now(), now() + interval '7 days', false
-- );


